### ISSUE TITLE
Adding new fields without resetting the whole store

### ISSUE THREAD

**Issue by abemscac** [samatechtw/vue-store#16]
Make it easier to add new fields to an existing store. It would be pretty convenient to do that without needing to reset the whole store.

**Comment by sampullman** [comment]
Thanks for making the issue! I guess I forgot to do it before 😬

**Comment by abemscac** [comment]
No worries! I just copied your comment and pasted it here anyway. 😅 

I think this feature is for the LocalStoragePlugin. Instead of building a full migration system like `knex`, would it make sense to just make the plugins configurable and leave the handling to the users? That way, users won't have to learn a new system when using the library.

As a recap, currently the code look like this:

```ts
const userModule = useModule({
  name: 'user',
  version: 1,
  stateInit: getDefaultUser,
  getters,
  mutations,
  plugins: [LocalStoragePlugin],
})
```

We didn't provide a built-in way for users to configure plugins. For example, if we were to add a `onInitVersionChange: (prevStore) => IState` option in `LocalStoragePlugin`, a possible workaround might be like this:

```ts
import {
  configureLocalStoragePlugin,
  LocalStoragePlugin,
} from '@samatech/vue-store'

configureLocalStoragePlugin({
  onInitVersionChange: (prevStore) => {
    // Implement custom logic here.
    if (prevStore.version < 5) {
      // Don't reset
      return prevStore.state
    }
    // Reset
    return newState
  }
})

const userModule = useStore({
  // ...
  plugins: [LocalStoragePlugin],
})
```

Developers can declare options as module-level variables, export a function to change those values (i.e. the `configureLocalStoragePlugin` in this example), and finally use them inside the plugin.

However, one of the downsides is that since module-level variables are like singleton, and a plugin can be used multiple times in different modules in a store, developers will have to make sure plugin used in different modules reads different options. So I think it's not so ideal.

---

Another possibility is to add an option like `pluginConfigs` in `useModule`, which is expected to achieve the same purpose. For example:

```ts
import { LocalStoragePlugin } from '@samatech/vue-store'

const userModule = useStore({
  // ...
  plugins: [LocalStoragePlugin, AnotherPlugin],
  pluginConfigs: {
    [LocalStoragePlugin.name]: {
      onInitVersionChange: (prevStore) => {
        // ...
      },
    },
    [AnotherPlugin.name]: {
      // ...
    }
  },
})
```

The `pluginConfigs` option is expected to collect the configs for all plugins, and we can make use of `Function.name` to "extract" the correct set of config from `pluginConfigs`, and put it in the plugin as an argument:

```ts
export const LocalStoragePlugin = <S extends IState>(
  module: IGenericModule<S>,
  configs: Record<string, any>, // <- This value will be `pluginConfigs[LocalStoragePlugin.name]`
): IPlugin<S> => {
  // ...
}
```

However, I think this approach would only work for named plugins, and it may be difficult to get the typing right.

---

Is this something we want? Or we just want to remove the auto-reset feature from `LocalStoragePlugin`? 😅

**Comment by sampullman** [comment]
> I think this feature is for the LocalStoragePlugin.

Right 👍 

> Instead of building a full migration system like knex, would it make sense to just make the plugins configurable and leave the handling to the users?

Originally I wanted to implement a migration system, but the point of this issue was to only support the common case of adding a field, without too much complication. Other things real migrations could support are removing, renaming, changing types, and transforming field data.

To do this, I figured we could check if the version is changed, find the new fields, and initialize those (but keep the old data). But that's not so easy because then we need a way to differentiate between a "reset" and adding fields. It's possible, but kind of messy.

> We didn't provide a built-in way for users to configure plugins...

The `configureLocalStoragePlugin` (or `pluginConfigs`) could work, although I'd prefer the external interface to look like:
```ts
const storagePlugin = makeLocalStoragePlugin({
  onVersionChange: (prevStore) => {
    // Implement custom logic here.
    if (prevStore.version < 5) {
      // Don't reset
      return prevStore.state
    }
    // Reset
    return newState
  }
})

const userModule = useModule({
  // ...
  plugins: [storagePlugin],
})
```

or maybe
```ts
const storagePlugin = {
  ...LocalStoragePlugin,
  onVersionChange: (prevStore) => {
    // Implement custom logic here.
    if (prevStore.version < 5) {
      // Don't reset
      return prevStore.state
    }
    // Reset
    return newState
  }
})
```

So overall the process for adding (or deleting/changing) fields is:
- Update State interface
- Add defaults
- Use `onVersionChange` to set default/etc

Now that I write it out, I wonder if we can add a helper function like `migrateStorageState(newFields: Partial<IState>)` that compares the previous fields to the new ones, removes deleted fields, and sets defaults for added fields.

If that's the case maybe it can just be built into the plugin 🤔

**Comment by sampullman** [comment]
Sounds good! If it ends up being more difficult than expected, I think just providing an optional `onVersionChanged` callback for the local storage plugin is good enough.
