### ISSUE TITLE
Undefined fields missing from flattened module

### ISSUE THREAD

**Issue by sampullman** [samatechtw/vue-store#20]
Fields don't appear in flattened modules if they are set to undefined.

Fields in the schema should always be present in the module.

**Comment by abemscac** [comment]
Hi @sampullman 

It seems that this happened because `JSON.stringify` is skipping all attributes whose value is `undefined`.
How come I didn't realize that 😅.

It's kind of weird to tell users "all values in your module cannot be `undefined` if you decide to use LocalStoragePlugin". That actually makes sense at some point, because that's the nature of JavaScript; but it's not so intuitive.

One possible solution is to replace `undefined` with an unique value (i.e. `"__undefined__"`) when serializing the states, and replace them with the real `undefined` during deserialization.

Is there any better solution?

**Comment by sampullman** [comment]
This is why I normally use `null` in the store, although it's annoying that this is often the only part of the codebase that has `null` instead of `undefined`. But I don't quite understand why the typechecker allowed the fields to be `undefined`. Was it because we set a field from another object that was improperly typed?

**Comment by abemscac** [comment]
I think it's because the use of `Partial`:

```ts
updateUser: (userData: Partial<UserState>) => {
  // ...
},
```

The `UserState` was correctly typed; no attribute is allowed to be `undefined`.
Maybe we can try to remove `Partial` and replace places where `undefined` with `null` when necessary to solve this issue?

**Comment by sampullman** [comment]
Yeah, that sounds like a good idea. Maybe we can leave a note about `undefined` behavior in the README for now.

Using your suggestion of saving as `__undefined__` is an interesting idea though, maybe it could be added as an optional feature of the local storage plugin in the future.

**Comment by abemscac** [comment]
Got it, no problem.
I'll probably create an issue about removing `Partial` in the store of FR repository later on.
Thank you!

**Comment by sampullman** [comment]
Got it, I'll close this one after I add a note to the Readme
